### ISSUE TITLE
User Registration — Backend 🔴

### ISSUE THREAD

**Issue by AndreLuisPLuz** [Engineering-Technical-School-Bosch-CWB/skillhub#27]
User registration functionalities in the back-end shall make use of the already defined CRUD interface in the services. However, some fine points must be considered.

These two endpoints must be deployed:

`POST /user`
This endpoint creates an incomplete user, whose full informations will be updated later on. The request's body will contain:
```
{
    "sectorId": <int>
    "positionId": <int>,
    "name": <string>,
    "edv": <string>
}
```
The default password for the user is equal to the user's IDV.
On creation success, a 201 CREATED status should be returned, with the body:
```
{
    "userId": <int>,
    "sector": <string>,
    "position": <string>
}
```

`PATCH /user/{id}`
This endpoint updates any properties changed by a user. As such, the request's might vary, but must include at least one the user's properties. Only instructors or the very user might change their information.
On update success, a 200 OK status should be returned, with the body:
```
{
    "name": <string>,
    "edv": <string>,
    "card": <string>,
    "birthday": <string>,
    "newUser": <boolean>,
    "isActive": <boolean>
}
```

- [x] `POST /user`
- [x] `PATCH /user/{id}`

**Comment by YasminTrembulack** [comment]
PATCH payload changed to:
 ```
{
       "name": <string>, 
       "edv": <string>,
       "card": <string>,
       "birthday": <string>,
       "newUser": <boolean>,
       "isActive": <boolean>,
       "password": <string>,
       "sectorId": <integer>,
       "positionId": <integer>,
       "occupationId": <integer>
}
```
